# coding: utf-8

"""
    Bloom Energy Appstore

    Example API that uses an Appstore

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_app(self):
        """Test case for add_app

        """
        pass

    def test_delete_app(self):
        """Test case for delete_app

        """
        pass

    def test_find_app_by_id(self):
        """Test case for find_app_by_id

        """
        pass

    def test_find_apps(self):
        """Test case for find_apps

        """
        pass


if __name__ == '__main__':
    unittest.main()
