from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NewApp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, tag=None):  # noqa: E501
        """NewApp - a model defined in OpenAPI

        :param name: The name of this NewApp.  # noqa: E501
        :type name: str
        :param tag: The tag of this NewApp.  # noqa: E501
        :type tag: str
        """
        self.openapi_types = {
            'name': str,
            'tag': str
        }

        self.attribute_map = {
            'name': 'name',
            'tag': 'tag'
        }

        self._name = name
        self._tag = tag

    @classmethod
    def from_dict(cls, dikt) -> 'NewApp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewApp of this NewApp.  # noqa: E501
        :rtype: NewApp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this NewApp.


        :return: The name of this NewApp.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NewApp.


        :param name: The name of this NewApp.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tag(self) -> str:
        """Gets the tag of this NewApp.


        :return: The tag of this NewApp.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag: str):
        """Sets the tag of this NewApp.


        :param tag: The tag of this NewApp.
        :type tag: str
        """

        self._tag = tag
