# coding: utf-8

# flake8: noqa
"""
    Bloom Energy Appstore

    Example API that uses an Appstore

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.app import App
from openapi_client.models.error import Error
from openapi_client.models.new_app import NewApp
