openapi: 3.0.0
info:
  contact:
    email: apiteam@swagger.io
    name: Swagger API Team
    url: http://swagger.io
  description: Example API that uses an Appstore
  license:
    name: Proprietary
    url: https://www.bloomenergy.com/licenses/LICENSE.html
  termsOfService: http://swagger.io/terms/
  title: Bloom Energy Appstore
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
paths:
  /Apps:
    get:
      description: |
        Returns all Apps from the system that the user has access to
        Write more documentation here
        And here!
      operationId: find_apps
      parameters:
      - description: tags to filter by
        explode: true
        in: query
        name: tags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: maximum number of results to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/App'
                type: array
          description: App response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Creates a new App in the store. Duplicates are allowed
      operationId: add_app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewApp'
        description: App to add to the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
          description: App response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /Apps/{appId}:
    delete:
      description: deletes a single App based on the ID supplied
      operationId: delete_app
      parameters:
      - description: ID of App to delete
        explode: false
        in: path
        name: appId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: App deleted
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      description: "Returns a user based on a single ID, if the user does not have\
        \ access to the App"
      operationId: find_app_by_id
      parameters:
      - description: ID of App to fetch
        explode: false
        in: path
        name: appId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
          description: App response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    App:
      allOf:
      - $ref: '#/components/schemas/NewApp'
      - properties:
          appId:
            format: int64
            type: integer
        required:
        - appId
        type: object
      title: App
    NewApp:
      example:
        name: name
        tag: tag
      properties:
        name:
          title: name
          type: string
        tag:
          title: tag
          type: string
      required:
      - name
      title: NewApp
      type: object
    Error:
      properties:
        code:
          format: int32
          title: code
          type: integer
        message:
          title: message
          type: string
      required:
      - code
      - message
      title: Error
      type: object
